In [1]:
import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
import random

In [2]:
Data = pd.read_excel('T1.xlsx')

In [3]:
# Data["target"].replace({2: 0}, inplace=True)
target = Data['target'].to_list()
Data = Data.drop('target' ,axis=1)
# Data=Data.drop('TEXT' ,axis=1)
Data

,number of followers,status count,user effect,number of following,number of re-tweets,listed counts,tweet length,time span,registration age
0,979,721,0.951409,1029,13,0,139,155,155
1,1357,3567,0.337143,4025,37,5,140,95,95
2,198,38923,1.816514,109,16,0,139,1191,1193
3,104,2253,0.812500,128,16,0,139,153,155
4,980,15816,1.250000,784,16,0,139,116,118
...,...,...,...,...,...,...,...,...,...
687,2658,16187,0.876938,3031,2,0,140,769,777
688,234,1846,0.274971,851,1,1,140,429,437
689,892,2186,0.800718,1114,2,3,94,4448,4456
690,1608,23516,0.704645,2282,7,1,139,3692,3700
691,3149,21841,0.939439,3352,7,6,140,727,735

In [4]:
x = Data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
data = pd.DataFrame(x_scaled)

In [5]:
data

,0,1,2,3,4,5,6,7,8
0,0.003824,0.001339,0.000026,0.093232,0.151163,0.000000,0.989474,0.026697,0.025826
1,0.005301,0.006662,0.000009,0.364682,0.430233,0.005612,1.000000,0.016362,0.015496
2,0.000773,0.072786,0.000050,0.009876,0.186047,0.000000,0.989474,0.205133,0.204545
3,0.000406,0.004204,0.000022,0.011597,0.186047,0.000000,0.989474,0.026352,0.025826
4,0.003828,0.029570,0.000034,0.071034,0.186047,0.000000,0.989474,0.019979,0.019456
...,...,...,...,...,...,...,...,...,...
687,0.010383,0.030264,0.000024,0.274622,0.023256,0.000000,1.000000,0.132449,0.132920
688,0.000914,0.003443,0.000008,0.077104,0.011628,0.001122,1.000000,0.073889,0.074380
689,0.003484,0.004079,0.000022,0.100933,0.023256,0.003367,0.515789,0.766104,0.766357
690,0.006281,0.043971,0.000019,0.206759,0.081395,0.001122,0.989474,0.635894,0.636191
691,0.012301,0.040838,0.000026,0.303706,0.081395,0.006734,1.000000,0.125215,0.125689

In [9]:
X = Data
gm = GaussianMixture(n_components=2, random_state=0).fit_predict(X)

In [11]:
accuracy_score(target, gm)

0.8049132947976878

In [288]:
# data['target'] = gm

In [292]:
# Data['target'] = gm
# gm[102]

0