In [206]:
import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
import random

In [296]:
Data = pd.read_excel('Datasets/ghanisazi/ghanisaziAll.xlsx')

In [306]:
# Data["target"].replace({2: 0}, inplace=True)
# target = Data['target'].to_list()
# Data = Data.drop('target' ,axis=1)
# Data=Data.drop('TEXT' ,axis=1)
Data

,number of followers,status count,user effect,number of following,number of re-tweets,listed counts,tweet length,time span,registration age
0,77,3643,1.115942,69,19,0,140,115,115
1,17,3431,0.485714,35,618,2,140,410,410
2,42,2718,0.211055,199,1,0,139,5000,5000
3,64,1331,0.243346,263,4,0,139,152,152
4,7005,102529,1.069629,6549,0,10,119,1131,1131
...,...,...,...,...,...,...,...,...,...
8764,23,468,0.522727,44,0,1,140,863,873
8765,2846,183,118.583333,24,1,6,140,118,128
8766,3386,24828,0.709853,4770,0,1,140,2518,2528
8767,1217,7550,0.926180,1314,0,3,140,1561,1572
8768,12,250,0.222222,54,0,0,140,154,164

In [298]:
x = Data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
data = pd.DataFrame(x_scaled)

In [299]:
data

,0,1,2,3,4,5,6,7,8
0,0.000035,0.004974,4.604021e-06,0.000929,0.006653,0.000000,1.000000,0.019675,0.019333
1,0.000008,0.004685,2.003902e-06,0.000471,0.216387,0.000615,1.000000,0.070145,0.069803
2,0.000019,0.003711,8.707468e-07,0.002680,0.000350,0.000000,0.992481,0.855432,0.855090
3,0.000029,0.001816,1.003968e-06,0.003542,0.001401,0.000000,0.992481,0.026005,0.025663
4,0.003197,0.140028,4.412948e-06,0.088194,0.000000,0.003077,0.842105,0.193499,0.193157
...,...,...,...,...,...,...,...,...,...
8764,0.000010,0.000638,2.156606e-06,0.000593,0.000000,0.000308,1.000000,0.147648,0.149016
8765,0.001299,0.000249,4.892371e-04,0.000323,0.000350,0.001846,1.000000,0.020188,0.021557
8766,0.001545,0.033907,2.928628e-06,0.064236,0.000000,0.000308,1.000000,0.430796,0.432164
8767,0.000555,0.010310,3.821122e-06,0.017695,0.000000,0.000923,1.000000,0.267066,0.268606
8768,0.000005,0.000340,9.168181e-07,0.000727,0.000000,0.000000,1.000000,0.026347,0.027716

In [303]:
X = Data
gm = GaussianMixture(n_components=2, random_state=0).fit_predict(X)

In [304]:
# predicted = []
# for i in range (len(gm)):
#     if(gm[i] == 0 or gm[i] == 1 or gm[i] == 2 ):
#         predicted.append(0)
#     else:
#         predicted.append(1)
    
# pred = []   
# for i in range(len(predicted)):
#     n = random.randint(0,100)
#     if(n < 25):
#         if(predicted[i] == 0):
#             pred.append(1)
#         else:
#             pred.append(0)
#     else:
#         pred.append(predicted[i])

In [305]:
accuracy_score(target, gm)

0.6220777739765082

In [288]:
# data['target'] = gm

In [292]:
# Data['target'] = gm
# gm[102]

0

In [295]:
# data.to_excel('Dataset2normal.xlsx', index=False)
# Data.to_excel('Dataset2.xlsx', index=False)